# Generated by Django 5.1.7 on 2025-03-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
    ]
